using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Silver_Task.Server.Models.Entities;
using Silver_Task.Server.Models.Entities.Enums;

namespace Silver_Task.Server.Data.Seeding
{
    /// <summary>
    /// Phase 60 — bulk synthetic volume for performance testing, run via
    /// `dotnet run -- --perf-seed=small|medium|large` (see Program.cs — gated to Development,
    /// exactly like --seed/DemoDataSeeder, never runs as part of normal startup). Deliberately a
    /// separate seeder from DemoDataSeeder, not an extension of it: DemoDataSeeder's job is a
    /// small, curated, realistic-looking dataset for manual exploration; this one's job is raw
    /// volume at a configurable scale, and every row it creates is unmistakably synthetic —
    /// project names prefixed "[Perf Test]", user emails on the reserved, non-routable
    /// ".invalid" TLD (RFC 2606) — so it can never be mistaken for real data and is trivially
    /// found/removed again via --perf-cleanup.
    ///
    /// Idempotent per profile (skips if that exact profile's project already exists) rather than
    /// additive-forever like DemoDataSeeder — a performance dataset is meant to be a known,
    /// reproducible size, not accumulate across repeated runs. Run --perf-cleanup first to
    /// regenerate at a different size.
    ///
    /// User emails are profile-scoped (perf-test-{profile}-user-NNNN@example.invalid), not just
    /// numbered 0001..N — different profiles' user counts overlap (small=10, medium=25, large=50),
    /// so two profiles seeded without an intervening --perf-cleanup would otherwise collide on the
    /// same email for user 0001..10 and violate the unique email constraint. Scoping by profile
    /// lets small/medium/large coexist simultaneously, which is a reasonable thing to want (e.g.
    /// comparing timings across sizes without tearing one down first).
    /// </summary>
    public static class PerformanceDataSeeder
    {
        private const string SeedPassword = "PerfTest1234!";
        private const string EmailDomain = "example.invalid";
        private const string ProjectNamePrefix = "[Perf Test]";

        private static readonly Dictionary<string, (int TaskCount, int UserCount)> Profiles = new(StringComparer.OrdinalIgnoreCase)
        {
            ["small"] = (100, 10),
            ["medium"] = (1000, 25),
            ["large"] = (5000, 50),
        };

        public static async Task<string> SeedAsync(IServiceProvider rootServices, string profile)
        {
            if (!Profiles.TryGetValue(profile, out var sizes))
            {
                throw new ArgumentException($"Unknown performance dataset profile \"{profile}\" — expected small, medium, or large.");
            }
            var (taskCount, userCount) = sizes;
            var projectName = $"{ProjectNamePrefix} {profile.ToUpperInvariant()} Dataset";

            using var scope = rootServices.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
            var passwordHasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher<User>>();

            var existingProject = await db.Projects.FirstOrDefaultAsync(p => p.Name == projectName);
            if (existingProject is not null)
            {
                var existingCount = await db.Tasks.CountAsync(t => t.ProjectId == existingProject.Id);
                Console.WriteLine($"\"{projectName}\" already exists ({existingCount} tasks) — skipping (idempotent). Run --perf-cleanup first to regenerate.");
                return projectName;
            }

            Console.WriteLine($"=== Silver-Task performance data seeder: {profile.ToUpperInvariant()} ({taskCount} tasks, {userCount} users) ===");
            var now = DateTime.UtcNow;
            var today = DateOnly.FromDateTime(now);

            var users = new List<User>(userCount);
            for (var i = 1; i <= userCount; i++)
            {
                var user = new User
                {
                    Id = Guid.NewGuid(),
                    Name = $"Perf Test User {i:D4}",
                    Email = $"perf-test-{profile.ToLowerInvariant()}-user-{i:D4}@{EmailDomain}",
                    PasswordHash = string.Empty,
                    Role = UserRole.Member,
                    IsActive = true,
                    CreatedAt = now
                };
                user.PasswordHash = passwordHasher.HashPassword(user, SeedPassword);
                users.Add(user);
            }
            db.Users.AddRange(users);

            var owner = users[0];
            var project = new Project
            {
                Id = Guid.NewGuid(),
                Name = projectName,
                Description = "Synthetic data generated by PerformanceDataSeeder (Phase 60) for load/scale testing. Safe to delete via `dotnet run -- --perf-cleanup`.",
                OwnerId = owner.Id,
                CreatedAt = now
            };
            db.Projects.Add(project);
            foreach (var user in users)
            {
                db.ProjectMembers.Add(new ProjectMember { Id = Guid.NewGuid(), ProjectId = project.Id, UserId = user.Id, CreatedAt = now });
            }

            // Two custom fields (Text + Dropdown) so the sheet view's custom-field columns, and
            // search's custom-value pass, have real synthetic data to exercise too — not just the
            // built-in fields.
            var notesField = new CustomField
            {
                Id = Guid.NewGuid(),
                ProjectId = project.Id,
                Name = "Perf Notes",
                Identifier = "perf_notes",
                FieldType = CustomFieldType.Text,
                SortOrder = 0
            };
            db.CustomFields.Add(notesField);

            var categoryField = new CustomField
            {
                Id = Guid.NewGuid(),
                ProjectId = project.Id,
                Name = "Perf Category",
                Identifier = "perf_category",
                FieldType = CustomFieldType.Dropdown,
                SortOrder = 1
            };
            var categoryNames = new[] { "Alpha", "Beta", "Gamma", "Delta" };
            var categoryOptions = new List<CustomFieldOption>();
            for (var i = 0; i < categoryNames.Length; i++)
            {
                var option = new CustomFieldOption { Id = Guid.NewGuid(), CustomFieldId = categoryField.Id, Value = categoryNames[i], SortOrder = i };
                categoryField.Options.Add(option);
                categoryOptions.Add(option);
            }
            db.CustomFields.Add(categoryField);

            var statuses = Enum.GetValues<TaskItemStatus>();
            var priorities = Enum.GetValues<TaskPriority>();

            for (var i = 1; i <= taskCount; i++)
            {
                var assignee = users[i % users.Count];
                var status = statuses[i % statuses.Length];
                var dueOffset = (i % 61) - 30; // spread roughly -30..+30 days so overdue/due-soon/upcoming filters all have real matches

                var task = new TaskItem
                {
                    Id = Guid.NewGuid(),
                    ProjectId = project.Id,
                    Title = $"Perf Test Task {i:D5}",
                    Description = $"Synthetic task {i} of {taskCount}, generated by PerformanceDataSeeder for Phase 60 load testing.",
                    Status = status,
                    Priority = priorities[i % priorities.Length],
                    AssignedToUserId = assignee.Id,
                    DueDate = today.AddDays(dueOffset),
                    CompletedAt = status == TaskItemStatus.Complete ? now.AddMinutes(-i) : null,
                    SortOrder = i,
                    CreatedAt = now.AddMinutes(-i),
                    UpdatedAt = now.AddMinutes(-i)
                };
                db.Tasks.Add(task);

                db.TaskCustomValues.Add(new TaskCustomValue
                {
                    Id = Guid.NewGuid(),
                    TaskId = task.Id,
                    CustomFieldId = notesField.Id,
                    Value = $"Perf note for task {i:D5}",
                    CreatedAt = now,
                    UpdatedAt = now
                });
                db.TaskCustomValues.Add(new TaskCustomValue
                {
                    Id = Guid.NewGuid(),
                    TaskId = task.Id,
                    CustomFieldId = categoryField.Id,
                    Value = categoryOptions[i % categoryOptions.Count].Value,
                    CreatedAt = now,
                    UpdatedAt = now
                });
            }

            await db.SaveChangesAsync();
            Console.WriteLine($"Seeded {taskCount} tasks and {userCount} users into \"{projectName}\" (owner: {owner.Email}, password: {SeedPassword}).");
            return projectName;
        }

        /// <summary>Removes every row this seeder could ever have created, matched purely by the
        /// same unmistakable markers used to create them (project name prefix, email domain) —
        /// never touches anything else, so it's safe to run even if real projects/users happen to
        /// exist alongside perf-test data.</summary>
        public static async Task CleanupAsync(IServiceProvider rootServices)
        {
            using var scope = rootServices.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

            var projects = await db.Projects.Where(p => p.Name.StartsWith(ProjectNamePrefix)).ToListAsync();
            var projectIds = projects.Select(p => p.Id).ToList();

            var taskIds = await db.Tasks.Where(t => projectIds.Contains(t.ProjectId)).Select(t => t.Id).ToListAsync();
            // CustomField.ProjectId is nullable (a null ProjectId means a global field, out of
            // scope here) — only ever filter on ones that actually belong to a perf-test project.
            var customFieldIds = await db.CustomFields.Where(f => f.ProjectId != null && projectIds.Contains(f.ProjectId.Value)).Select(f => f.Id).ToListAsync();

            db.TaskCustomValues.RemoveRange(db.TaskCustomValues.Where(v => taskIds.Contains(v.TaskId)));
            db.TaskActivities.RemoveRange(db.TaskActivities.Where(a => taskIds.Contains(a.TaskId)));
            db.CustomFieldOptions.RemoveRange(db.CustomFieldOptions.Where(o => customFieldIds.Contains(o.CustomFieldId)));
            db.CustomFields.RemoveRange(db.CustomFields.Where(f => f.ProjectId != null && projectIds.Contains(f.ProjectId.Value)));
            db.Tasks.RemoveRange(db.Tasks.Where(t => projectIds.Contains(t.ProjectId)));
            db.ProjectMembers.RemoveRange(db.ProjectMembers.Where(m => projectIds.Contains(m.ProjectId)));
            db.Projects.RemoveRange(projects);
            db.Users.RemoveRange(db.Users.Where(u => u.Email.EndsWith("@" + EmailDomain)));

            var removedTaskCount = taskIds.Count;
            var removedProjectCount = projects.Count;
            await db.SaveChangesAsync();
            Console.WriteLine($"Removed {removedProjectCount} performance-test project(s), {removedTaskCount} task(s), and their users.");
        }
    }
}
