using Microsoft.EntityFrameworkCore;
using Npgsql;
using Silver_Task.Server.Common;
using Silver_Task.Server.Common.Exceptions;
using Silver_Task.Server.Data;
using Silver_Task.Server.Models.DTOs.Recurrence;
using Silver_Task.Server.Models.DTOs.Tasks;
using Silver_Task.Server.Models.Entities;
using Silver_Task.Server.Models.Entities.Enums;

namespace Silver_Task.Server.Services
{
    public interface IRecurringTaskService
    {
        /// <summary>Null if the task isn't part of a recurring series.</summary>
        Task<RecurringTask?> GetForTaskAsync(Guid taskId, Guid callerId, UserRole callerRole);

        /// <summary>Attaches a recurrence rule to an existing task, which becomes the series'
        /// template/first occurrence (see RecurringTask.TemplateTaskId).</summary>
        Task<RecurringTask> CreateAsync(Guid taskId, CreateRecurrenceRequest request, Guid callerId, UserRole callerRole);

        /// <summary><paramref name="taskId"/> can be any occurrence in the series (every
        /// occurrence, not just the template, carries RecurringTaskId) — the actual rule it
        /// resolves to is looked up from there, matching the "everything scoped under
        /// /tasks/{taskId}/recurrence" API shape.</summary>
        Task<RecurringTask> UpdateAsync(Guid taskId, UpdateRecurrenceRequest request, Guid callerId, UserRole callerRole);

        /// <summary>Existing generated tasks are untouched; only future generation halts.</summary>
        Task<RecurringTask> StopAsync(Guid taskId, Guid callerId, UserRole callerRole);

        Task<RecurringTask> ResumeAsync(Guid taskId, Guid callerId, UserRole callerRole);

        /// <summary>Hard-deletes the rule row itself (SetNull on every generated task's
        /// RecurringTaskId — see TaskItemConfiguration). Never deletes a generated Task.</summary>
        Task DeleteAsync(Guid taskId, Guid callerId, UserRole callerRole);

        /// <summary>Every task ever generated by this rule (including the template), oldest first —
        /// backs "View series".</summary>
        Task<IReadOnlyList<TaskItem>> GetSeriesAsync(Guid taskId, Guid callerId, UserRole callerRole);

        /// <summary>Every recurring rule defined in a project — backs the Recurring Tasks
        /// management list.</summary>
        Task<IReadOnlyList<RecurringTask>> GetForProjectAsync(Guid projectId, Guid callerId, UserRole callerRole);

        /// <summary>Called by RecurringTaskGenerationBackgroundService (and the Administrator-only
        /// manual-trigger endpoint) — never exposed to normal users. Returns how many new task
        /// occurrences were actually created.</summary>
        Task<int> GenerateDueOccurrencesAsync();
    }

    public class RecurringTaskService(
        AppDbContext db,
        IProjectAccessService projectAccess,
        ITaskService taskService,
        ISystemSettingsService systemSettings,
        INotificationService notificationService,
        ILogger<RecurringTaskService> logger) : IRecurringTaskService
    {
        // Occurrences older than this are considered "no longer meaningful" and are skipped
        // (schedule advances past them, but no task is created) rather than backfilled — the
        // "server was down for 3 weeks" case the spec calls out.
        private const int CatchUpGraceDays = 7;

        // A safety valve, not an expected path — bounds how many occurrences a single rule can
        // generate in one background sweep, so a corrupted rule (or a very small generation
        // window combined with a very dense daily schedule) can never turn into an unbounded loop.
        private const int MaxOccurrencesPerRulePerRun = 200;

        private readonly AppDbContext _db = db;
        private readonly IProjectAccessService _projectAccess = projectAccess;
        private readonly ITaskService _taskService = taskService;
        private readonly ISystemSettingsService _systemSettings = systemSettings;
        private readonly INotificationService _notificationService = notificationService;
        private readonly ILogger<RecurringTaskService> _logger = logger;

        public async Task<RecurringTask?> GetForTaskAsync(Guid taskId, Guid callerId, UserRole callerRole)
        {
            var task = await LoadTaskForPermissionCheckAsync(taskId);
            await _projectAccess.EnsureCanParticipateAsync(task.ProjectId, task.Project!.OwnerId, callerId, callerRole);

            if (task.RecurringTaskId is not Guid recurringTaskId)
            {
                return null;
            }

            return await LoadRuleAsync(recurringTaskId);
        }

        public async Task<RecurringTask> CreateAsync(Guid taskId, CreateRecurrenceRequest request, Guid callerId, UserRole callerRole)
        {
            var task = await LoadTaskForPermissionCheckAsync(taskId);
            await _projectAccess.EnsureCanEditAsync(task.ProjectId, task.Project!.OwnerId, callerId, callerRole);

            if (task.RecurringTaskId is not null)
            {
                throw new ConflictException("This task is already part of a recurring series.");
            }

            ValidateRule(request.Frequency, request.Interval, request.DaysOfWeek, request.DayOfMonth, request.MonthOfYear, request.StartDate, request.EndDate, request.MaxOccurrences);

            if (request.AssignedToUserId is Guid assigneeId)
            {
                await EnsureAssigneeIsMemberAsync(task.ProjectId, assigneeId);
            }

            var rule = new RecurringTask
            {
                Id = Guid.NewGuid(),
                ProjectId = task.ProjectId,
                ParentTaskId = task.ParentTaskId,
                TemplateTaskId = task.Id,
                Title = request.Title.Trim(),
                Description = NormalizeText(request.Description),
                Priority = request.Priority,
                AssignedToUserId = request.AssignedToUserId,
                Frequency = request.Frequency,
                Interval = Math.Max(1, request.Interval),
                DaysOfWeek = RecurrenceCalculator.ToMask(request.DaysOfWeek),
                DayOfMonth = request.DayOfMonth,
                MonthOfYear = request.MonthOfYear,
                StartDate = request.StartDate,
                EndDate = request.EndDate,
                MaxOccurrences = request.MaxOccurrences,
                CreatedByUserId = callerId,
                // The task being attached to *is* occurrence #1 — its own StartDate/DueDate are
                // left exactly as the user already set them; only the series-membership fields
                // below are new.
                OccurrencesGenerated = 1
            };
            rule.NextOccurrenceDate = ComputeNextWithinLimits(rule, rule.StartDate);

            _db.RecurringTasks.Add(rule);

            task.RecurringTaskId = rule.Id;
            task.RecurrenceOccurrenceDate = rule.StartDate;
            task.OccurrenceNumber = 1;
            task.UpdatedAt = DateTime.UtcNow;

            _db.TaskActivities.Add(new TaskActivity
            {
                Id = Guid.NewGuid(),
                TaskId = task.Id,
                UserId = callerId,
                Action = "RecurrenceCreated",
                NewValue = RecurrenceDescriptionBuilder.Describe(rule)
            });

            await _db.SaveChangesAsync();
            return rule;
        }

        public async Task<RecurringTask> UpdateAsync(Guid taskId, UpdateRecurrenceRequest request, Guid callerId, UserRole callerRole)
        {
            var (_, rule) = await LoadTaskAndRuleAsync(taskId, callerId, callerRole, AccessTier.Edit);
            var recurringTaskId = rule.Id;

            ValidateRule(request.Frequency, request.Interval, request.DaysOfWeek, request.DayOfMonth, request.MonthOfYear, request.StartDate, request.EndDate, request.MaxOccurrences);

            if (request.AssignedToUserId is Guid assigneeId)
            {
                await EnsureAssigneeIsMemberAsync(rule.ProjectId, assigneeId);
            }

            var oldDescription = RecurrenceDescriptionBuilder.Describe(rule);

            var cutoffDate = request.Scope == RecurrenceEditScope.ThisAndFuture
                ? request.AnchorOccurrenceDate ?? throw new ValidationException("An anchor occurrence date is required to edit this and future occurrences.")
                : DateOnly.FromDateTime(DateTime.UtcNow);

            // Regenerate not-yet-touched future occurrences under the new rule. Deliberately
            // excludes the template task (TemplateTaskId) even if its own date falls at/after the
            // cutoff — it's the series' anchor and the subtask-structure source; removing it would
            // orphan both. "Not yet touched" = still at the system default status, the same signal
            // DeleteTaskDialog-adjacent logic elsewhere uses to distinguish "untouched" from "the
            // user already did something with this occurrence".
            var defaultStatus = await ResolveDefaultStatusAsync();
            var regenerateCandidates = await _db.Tasks
                .Where(t => t.RecurringTaskId == recurringTaskId
                    && t.Id != rule.TemplateTaskId
                    && t.RecurrenceOccurrenceDate != null
                    && t.RecurrenceOccurrenceDate >= cutoffDate
                    && t.Status == defaultStatus)
                .Select(t => t.Id)
                .ToListAsync();

            foreach (var occurrenceId in regenerateCandidates)
            {
                await DeleteOccurrenceAndSubtreeAsync(occurrenceId);
            }

            // Flush the deletions now — the queries just below (latestSurvivingDate,
            // OccurrencesGenerated) run as fresh SQL against the database, not against the
            // change tracker, so without this they'd still see the about-to-be-deleted rows
            // and compute the wrong resume point.
            if (regenerateCandidates.Count > 0)
            {
                await _db.SaveChangesAsync();
            }

            rule.Title = request.Title.Trim();
            rule.Description = NormalizeText(request.Description);
            rule.Priority = request.Priority;
            rule.AssignedToUserId = request.AssignedToUserId;
            rule.Frequency = request.Frequency;
            rule.Interval = Math.Max(1, request.Interval);
            rule.DaysOfWeek = RecurrenceCalculator.ToMask(request.DaysOfWeek);
            rule.DayOfMonth = request.DayOfMonth;
            rule.MonthOfYear = request.MonthOfYear;
            rule.StartDate = request.StartDate;
            rule.EndDate = request.EndDate;
            rule.MaxOccurrences = request.MaxOccurrences;
            rule.UpdatedAt = DateTime.UtcNow;

            // Resume generation from whatever the latest *surviving* occurrence date is (the
            // regenerated ones are gone now, so this naturally lands on either the cutoff's
            // predecessor or an earlier, untouched-but-before-cutoff occurrence).
            var latestSurvivingDate = await _db.Tasks
                .Where(t => t.RecurringTaskId == recurringTaskId && t.RecurrenceOccurrenceDate != null)
                .Select(t => t.RecurrenceOccurrenceDate!.Value)
                .OrderByDescending(d => d)
                .FirstOrDefaultAsync();
            var resumeFrom = latestSurvivingDate == default ? rule.StartDate.AddDays(-1) : latestSurvivingDate;

            rule.OccurrencesGenerated = await _db.Tasks.CountAsync(t => t.RecurringTaskId == recurringTaskId);
            rule.NextOccurrenceDate = ComputeNextWithinLimits(rule, resumeFrom);

            if (rule.TemplateTaskId is Guid templateId)
            {
                _db.TaskActivities.Add(new TaskActivity
                {
                    Id = Guid.NewGuid(),
                    TaskId = templateId,
                    UserId = callerId,
                    Action = "RecurrenceEdited",
                    OldValue = oldDescription,
                    NewValue = RecurrenceDescriptionBuilder.Describe(rule)
                });
            }

            await _db.SaveChangesAsync();
            return rule;
        }

        public async Task<RecurringTask> StopAsync(Guid taskId, Guid callerId, UserRole callerRole)
        {
            var (_, rule) = await LoadTaskAndRuleAsync(taskId, callerId, callerRole, AccessTier.Edit);

            if (rule.IsActive)
            {
                rule.IsActive = false;
                rule.NextOccurrenceDate = null;
                rule.UpdatedAt = DateTime.UtcNow;

                if (rule.TemplateTaskId is Guid templateId)
                {
                    _db.TaskActivities.Add(new TaskActivity { Id = Guid.NewGuid(), TaskId = templateId, UserId = callerId, Action = "RecurrenceStopped" });
                }

                await _db.SaveChangesAsync();
            }

            return rule;
        }

        public async Task<RecurringTask> ResumeAsync(Guid taskId, Guid callerId, UserRole callerRole)
        {
            var (_, rule) = await LoadTaskAndRuleAsync(taskId, callerId, callerRole, AccessTier.Edit);

            if (!rule.IsActive)
            {
                rule.IsActive = true;
                rule.UpdatedAt = DateTime.UtcNow;

                var latestDate = await _db.Tasks
                    .Where(t => t.RecurringTaskId == rule.Id && t.RecurrenceOccurrenceDate != null)
                    .Select(t => t.RecurrenceOccurrenceDate!.Value)
                    .OrderByDescending(d => d)
                    .FirstOrDefaultAsync();
                var resumeFrom = latestDate == default ? rule.StartDate.AddDays(-1) : latestDate;

                // Don't immediately flood-generate everything missed while stopped — resume as if
                // "today" were the baseline when the series was paused long enough that its actual
                // last occurrence is already in the past (the generator's own catch-up-window logic
                // in GenerateForRuleAsync then applies normally from here).
                var today = DateOnly.FromDateTime(DateTime.UtcNow);
                if (resumeFrom < today)
                {
                    resumeFrom = today.AddDays(-1);
                }

                rule.NextOccurrenceDate = ComputeNextWithinLimits(rule, resumeFrom);

                if (rule.TemplateTaskId is Guid templateId)
                {
                    _db.TaskActivities.Add(new TaskActivity { Id = Guid.NewGuid(), TaskId = templateId, UserId = callerId, Action = "RecurrenceResumed" });
                }

                await _db.SaveChangesAsync();
            }

            return rule;
        }

        public async Task DeleteAsync(Guid taskId, Guid callerId, UserRole callerRole)
        {
            var (_, rule) = await LoadTaskAndRuleAsync(taskId, callerId, callerRole, AccessTier.Manage);

            if (rule.TemplateTaskId is Guid templateId)
            {
                _db.TaskActivities.Add(new TaskActivity { Id = Guid.NewGuid(), TaskId = templateId, UserId = callerId, Action = "RecurrenceDeleted" });
            }

            _db.RecurringTasks.Remove(rule);
            await _db.SaveChangesAsync();
        }

        public async Task<IReadOnlyList<TaskItem>> GetSeriesAsync(Guid taskId, Guid callerId, UserRole callerRole)
        {
            var (_, rule) = await LoadTaskAndRuleAsync(taskId, callerId, callerRole);

            return await _db.Tasks
                .Include(t => t.AssignedTo)
                .Where(t => t.RecurringTaskId == rule.Id)
                .OrderBy(t => t.RecurrenceOccurrenceDate)
                .ToListAsync();
        }

        public async Task<IReadOnlyList<RecurringTask>> GetForProjectAsync(Guid projectId, Guid callerId, UserRole callerRole)
        {
            var project = await LoadProjectAsync(projectId);
            await _projectAccess.EnsureCanParticipateAsync(project.Id, project.OwnerId, callerId, callerRole);

            return await _db.RecurringTasks
                .Include(r => r.AssignedToUser)
                .Include(r => r.TemplateTask)
                .Where(r => r.ProjectId == projectId)
                .OrderByDescending(r => r.CreatedAt)
                .ToListAsync();
        }

        public async Task<int> GenerateDueOccurrencesAsync()
        {
            var windowDays = await _systemSettings.GetIntAsync(SystemSettingKeys.RecurringTaskGenerationWindowDays);
            var today = DateOnly.FromDateTime(DateTime.UtcNow);
            var windowEnd = today.AddDays(windowDays);
            var catchUpFloor = today.AddDays(-CatchUpGraceDays);

            // The entire due-rule scan — one indexed query, not one query per rule.
            var dueRules = await _db.RecurringTasks
                .Where(r => r.IsActive && r.NextOccurrenceDate != null && r.NextOccurrenceDate <= windowEnd)
                .ToListAsync();

            var generatedCount = 0;

            foreach (var rule in dueRules)
            {
                try
                {
                    generatedCount += await GenerateForRuleAsync(rule, windowEnd, catchUpFloor);
                }
                catch (Exception ex)
                {
                    // One rule's failure must never corrupt/abort the whole sweep — every other
                    // rule still gets a chance to generate this run, and this rule's own
                    // NextOccurrenceDate was never advanced (nothing here was saved), so it's
                    // retried from the same point on the next run.
                    _logger.LogError(ex, "Recurring task generation failed for rule {RuleId}.", rule.Id);
                }
            }

            return generatedCount;
        }

        private async Task<int> GenerateForRuleAsync(RecurringTask rule, DateOnly windowEnd, DateOnly catchUpFloor)
        {
            // Self-healing guard for an edge case with no UI path to fix it directly: if the
            // template task was deleted (TemplateTaskId SetNull) *and* every occurrence this rule
            // ever generated has also since been deleted, there is no task left anywhere whose
            // RecurringTaskId could resolve back to this rule — meaning Stop/Edit/Delete can never
            // be reached through the task-scoped API again. Rather than silently generating
            // orphaned top-level tasks forever, treat the rule as effectively stopped.
            if (rule.TemplateTaskId is null && !await _db.Tasks.AnyAsync(t => t.RecurringTaskId == rule.Id))
            {
                rule.IsActive = false;
                rule.NextOccurrenceDate = null;
                rule.UpdatedAt = DateTime.UtcNow;
                await _db.SaveChangesAsync();
                _logger.LogWarning("Recurring task {RuleId} has no reachable occurrences left (template deleted); auto-stopped.", rule.Id);
                return 0;
            }

            var generated = 0;
            var iterations = 0;

            while (rule.NextOccurrenceDate is DateOnly occurrenceDate && occurrenceDate <= windowEnd && iterations < MaxOccurrencesPerRulePerRun)
            {
                iterations++;

                if (occurrenceDate < catchUpFloor)
                {
                    // Too old to still be meaningful (the "server was down for 3 weeks" case) —
                    // skip forward without materializing a task. Still counts toward
                    // MaxOccurrences: the schedule slot "happened", we just chose not to backfill it.
                    rule.OccurrencesGenerated++;
                    rule.NextOccurrenceDate = ComputeNextWithinLimits(rule, occurrenceDate);
                    continue;
                }

                var alreadyExists = await _db.Tasks.AnyAsync(t => t.RecurringTaskId == rule.Id && t.RecurrenceOccurrenceDate == occurrenceDate);
                var isExcepted = await _db.RecurringTaskExceptions.AnyAsync(e => e.RecurringTaskId == rule.Id && e.OccurrenceDate == occurrenceDate);

                if (!alreadyExists && !isExcepted && await GenerateOccurrenceAsync(rule, occurrenceDate))
                {
                    generated++;
                }

                rule.OccurrencesGenerated++;
                rule.NextOccurrenceDate = ComputeNextWithinLimits(rule, occurrenceDate);
            }

            rule.UpdatedAt = DateTime.UtcNow;
            await _db.SaveChangesAsync();
            return generated;
        }

        /// <summary>Creates one occurrence (the top-level task plus a fresh copy of the template's
        /// subtask tree) inside its own database transaction, so a mid-tree failure never leaves a
        /// half-built occurrence — either the whole thing commits or none of it does.</summary>
        private async Task<bool> GenerateOccurrenceAsync(RecurringTask rule, DateOnly occurrenceDate)
        {
            await using var transaction = await _db.Database.BeginTransactionAsync();
            try
            {
                var newTaskId = await CreateOccurrenceTaskAsync(rule, occurrenceDate);
                if (newTaskId is not Guid createdTaskId)
                {
                    await transaction.RollbackAsync();
                    return false;
                }

                if (rule.TemplateTaskId is Guid templateId)
                {
                    await CopySubtaskTreeAsync(rule, templateId, createdTaskId);
                }

                _db.TaskActivities.Add(new TaskActivity
                {
                    Id = Guid.NewGuid(),
                    TaskId = createdTaskId,
                    UserId = null,
                    Action = "RecurringOccurrenceGenerated",
                    NewValue = rule.Title
                });
                await _db.SaveChangesAsync();

                await transaction.CommitAsync();
                return true;
            }
            catch (DbUpdateException ex) when (IsUniqueViolation(ex))
            {
                // A concurrent/retried run already created this exact occurrence — the database
                // constraint (not just this in-memory check) is the real guard here; racing into
                // it is a benign no-op, not an error.
                await transaction.RollbackAsync();
                _logger.LogInformation("Skipped duplicate occurrence for rule {RuleId} on {Date}.", rule.Id, occurrenceDate);
                return false;
            }
        }

        private async Task<Guid?> CreateOccurrenceTaskAsync(RecurringTask rule, DateOnly occurrenceDate)
        {
            var (actingUserId, actingRole) = await ResolveActingUserAsync(rule.CreatedByUserId);
            if (actingUserId is null)
            {
                _logger.LogWarning("Recurring task {RuleId}: creator {UserId} is no longer active; skipping generation.", rule.Id, rule.CreatedByUserId);
                return null;
            }

            var assignedToUserId = rule.AssignedToUserId;
            if (assignedToUserId is Guid candidateAssigneeId && !await IsValidActiveMemberAsync(rule.ProjectId, candidateAssigneeId))
            {
                assignedToUserId = null;
                await _notificationService.NotifyAsync(
                    rule.CreatedByUserId, null, NotificationTypes.RecurringTaskAssigneeInactive,
                    "Recurring task assignee unavailable",
                    $"\"{rule.Title}\" could not be auto-assigned — the assigned user is no longer an active project member. The new occurrence was created unassigned.",
                    null, rule.ProjectId);
            }

            var request = new CreateTaskRequest
            {
                Title = rule.Title,
                Description = rule.Description,
                Priority = rule.Priority,
                AssignedToUserId = assignedToUserId,
                StartDate = occurrenceDate,
                DueDate = occurrenceDate
            };

            var task = rule.ParentTaskId is Guid parentId && await _db.Tasks.AnyAsync(t => t.Id == parentId)
                ? await _taskService.CreateSubtaskAsync(parentId, request, actingUserId.Value, actingRole)
                : await _taskService.CreateAsync(rule.ProjectId, request, actingUserId.Value, actingRole);

            // `task` is already tracked by this same scoped DbContext (ITaskService shares it) —
            // setting these fields directly is picked up by the transaction's own SaveChangesAsync.
            task.RecurringTaskId = rule.Id;
            task.RecurrenceOccurrenceDate = occurrenceDate;
            task.OccurrenceNumber = rule.OccurrencesGenerated + 1;

            return task.Id;
        }

        /// <summary>Recreates the template's subtask tree (fresh, default-status copies — never
        /// the previous occurrence's completion state, comments, attachments, or activity history)
        /// under the newly generated occurrence, preserving nesting depth.</summary>
        private async Task CopySubtaskTreeAsync(RecurringTask rule, Guid sourceParentTaskId, Guid newParentTaskId)
        {
            var (actingUserId, actingRole) = await ResolveActingUserAsync(rule.CreatedByUserId);
            if (actingUserId is null)
            {
                return;
            }

            var templateChildren = await _db.Tasks
                .Where(t => t.ParentTaskId == sourceParentTaskId)
                .OrderBy(t => t.SortOrder)
                .Select(t => new { t.Id, t.Title, t.Description, t.Priority, t.AssignedToUserId })
                .ToListAsync();

            foreach (var templateChild in templateChildren)
            {
                var assignedToUserId = templateChild.AssignedToUserId is Guid candidateId && await IsValidActiveMemberAsync(rule.ProjectId, candidateId)
                    ? candidateId
                    : (Guid?)null;

                var childRequest = new CreateTaskRequest
                {
                    Title = templateChild.Title,
                    Description = templateChild.Description,
                    Priority = templateChild.Priority,
                    AssignedToUserId = assignedToUserId
                };

                var newChild = await _taskService.CreateSubtaskAsync(newParentTaskId, childRequest, actingUserId.Value, actingRole);

                // Recurse so nested subtasks (Subtask A1 under Subtask A) keep their place —
                // depth is already bounded by MaxNestingDepth via CreateSubtaskAsync itself.
                await CopySubtaskTreeAsync(rule, templateChild.Id, newChild.Id);
            }
        }

        private static bool IsUniqueViolation(DbUpdateException ex) =>
            ex.InnerException is PostgresException pgEx && pgEx.SqlState == PostgresErrorCodes.UniqueViolation;

        private static DateOnly? ComputeNextWithinLimits(RecurringTask rule, DateOnly afterDate)
        {
            if (rule.MaxOccurrences is int max && rule.OccurrencesGenerated >= max)
            {
                return null;
            }

            var next = RecurrenceCalculator.ComputeNextOccurrence(rule, afterDate);
            if (next is null)
            {
                return null;
            }

            if (rule.EndDate is DateOnly end && next > end)
            {
                return null;
            }

            return next;
        }

        private static void ValidateRule(
            RecurrenceFrequency frequency, int interval, List<DayOfWeek>? daysOfWeek,
            int? dayOfMonth, int? monthOfYear, DateOnly startDate, DateOnly? endDate, int? maxOccurrences)
        {
            var maxInterval = frequency switch
            {
                RecurrenceFrequency.Daily => 365,
                RecurrenceFrequency.Weekly => 52,
                RecurrenceFrequency.Monthly => 24,
                RecurrenceFrequency.Yearly => 10,
                _ => 1
            };
            if (interval < 1 || interval > maxInterval)
            {
                throw new ValidationException($"Repeat interval for {frequency} recurrence must be between 1 and {maxInterval}.");
            }

            if (frequency == RecurrenceFrequency.Weekly && (daysOfWeek is null || daysOfWeek.Count == 0))
            {
                throw new ValidationException("Select at least one day of the week for a weekly recurrence.");
            }

            if (dayOfMonth is int dom && (dom < 1 || dom > 31))
            {
                throw new ValidationException("Day of month must be between 1 and 31.");
            }

            if (monthOfYear is int moy && (moy < 1 || moy > 12))
            {
                throw new ValidationException("Month must be between 1 and 12.");
            }

            if (endDate is DateOnly end && end < startDate)
            {
                throw new ValidationException("End date cannot be before the start date.");
            }

            if (maxOccurrences is int max && (max < 1 || max > 1000))
            {
                throw new ValidationException("Occurrence count must be between 1 and 1000.");
            }
        }

        private async Task DeleteOccurrenceAndSubtreeAsync(Guid taskId)
        {
            var frontier = new List<Guid> { taskId };
            var toRemove = new List<Guid> { taskId };

            while (frontier.Count > 0)
            {
                var children = await _db.Tasks.Where(t => t.ParentTaskId != null && frontier.Contains(t.ParentTaskId!.Value)).Select(t => t.Id).ToListAsync();
                if (children.Count == 0)
                {
                    break;
                }
                toRemove.AddRange(children);
                frontier = children;
            }

            var rows = await _db.Tasks.Where(t => toRemove.Contains(t.Id)).ToListAsync();
            _db.Tasks.RemoveRange(rows);
        }

        private async Task<(Guid? UserId, UserRole Role)> ResolveActingUserAsync(Guid userId)
        {
            var user = await _db.Users.Where(u => u.Id == userId).Select(u => new { u.Id, u.Role, u.IsActive }).FirstOrDefaultAsync();
            return user is null || !user.IsActive ? (null, default) : (user.Id, user.Role);
        }

        private async Task<bool> IsValidActiveMemberAsync(Guid projectId, Guid userId)
        {
            if (!await _projectAccess.IsMemberAsync(projectId, userId))
            {
                return false;
            }
            return await _db.Users.Where(u => u.Id == userId).Select(u => u.IsActive).FirstOrDefaultAsync();
        }

        private async Task EnsureAssigneeIsMemberAsync(Guid projectId, Guid assigneeId)
        {
            if (!await IsValidActiveMemberAsync(projectId, assigneeId))
            {
                throw new ValidationException("The assigned user must be an active member of this project.");
            }
        }

        private async Task<TaskItemStatus> ResolveDefaultStatusAsync()
        {
            var value = await _systemSettings.GetStringAsync(SystemSettingKeys.DefaultTaskStatus);
            return Enum.TryParse<TaskItemStatus>(value, out var status) ? status : TaskItemStatus.NotStarted;
        }

        private async Task<RecurringTask> LoadRuleAsync(Guid recurringTaskId)
        {
            var rule = await _db.RecurringTasks.FirstOrDefaultAsync(r => r.Id == recurringTaskId);
            return rule ?? throw new NotFoundException($"Recurring task '{recurringTaskId}' was not found.");
        }

        private async Task<TaskItem> LoadTaskForPermissionCheckAsync(Guid taskId)
        {
            var task = await _db.Tasks.Include(t => t.Project).FirstOrDefaultAsync(t => t.Id == taskId);
            return task ?? throw new NotFoundException($"Task '{taskId}' was not found.");
        }

        private async Task<Project> LoadProjectAsync(Guid projectId)
        {
            var project = await _db.Projects.FirstOrDefaultAsync(p => p.Id == projectId);
            return project ?? throw new NotFoundException($"Project '{projectId}' was not found.");
        }

        private enum AccessTier { View, Edit, Manage }

        /// <summary>Resolves a task to the recurring rule it belongs to (any occurrence works, not
        /// just the template — every generated task carries RecurringTaskId) after checking the
        /// caller can act on that task's project at the requested tier: View (GetSeriesAsync),
        /// Edit (Update/Stop/Resume — a Viewer can never reach these), or Manage (Delete).</summary>
        private async Task<(TaskItem Task, RecurringTask Rule)> LoadTaskAndRuleAsync(Guid taskId, Guid callerId, UserRole callerRole, AccessTier tier = AccessTier.View)
        {
            var task = await LoadTaskForPermissionCheckAsync(taskId);

            switch (tier)
            {
                case AccessTier.Manage:
                    await _projectAccess.EnsureCanManageAsync(task.ProjectId, task.Project!.OwnerId, callerId, callerRole);
                    break;
                case AccessTier.Edit:
                    await _projectAccess.EnsureCanEditAsync(task.ProjectId, task.Project!.OwnerId, callerId, callerRole);
                    break;
                default:
                    await _projectAccess.EnsureCanParticipateAsync(task.ProjectId, task.Project!.OwnerId, callerId, callerRole);
                    break;
            }

            if (task.RecurringTaskId is not Guid recurringTaskId)
            {
                throw new NotFoundException($"Task '{taskId}' is not part of a recurring series.");
            }

            return (task, await LoadRuleAsync(recurringTaskId));
        }

        private static string? NormalizeText(string? text) =>
            string.IsNullOrWhiteSpace(text) ? null : text.Trim();
    }
}
